### ISSUE TITLE
PhishFeed contact page is empty

### ISSUE THREAD

**Issue by mimi89999** [bradleyjkemp/abwhose#11]
Hello,

I noticed that https://phish.report/contacts/PhishFeed is empty.

**Comment by bradleyjkemp** [comment]
Hey, good spot.

That's a bit of an odd case because they don't have a public way to report sites to them (phish.report uses an invite-only API). These contact pages now have a form to submit a URL using the phish.report APIs so I think that's about as good a solution as I can do here!
